#!/live/bin/sh

### BEGIN INIT INFO
# Provides:          live-init
# Required-Start:    checkroot checkroot-bootclean
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: live-init
# Description: localize /etc/skel, create /home/demo, customize X, mirrors, set default desktop
### END INIT INFO

PATH=/live/bin:$PATH

XSESSION_DIR=/usr/share/xsessions
    MENU_WMs="fluxbox icewm jwm"
    FF_PREFS="/etc/skel/.mozilla/firefox/*/prefs.js"
   AUTOMOUNT=

ALL_VIDEO_MODULES="ast|cirrus|gma500_gfx|ch7006|sil164|tda998x|i810|i915|mga|mgag200|nouveau|qxl|r128|radeon|savage|sis|tdfx|ttm|udl|via|vmwgfx"

KMS_VIDEO_MODULES="ast|cirrus|gma500_gfx|ch7006|tda998x|i915|mgag200|nouveau|qxl|radeon|udl|vmwgfx"

#-jbb For debugging
: ${CMDLINE:=$(cat /proc/cmdline /live/config/cmdline)}
for param in $CMDLINE; do
    value=${param#*=}
    case "$param" in
             desktop=*)  CMD_DESKTOP=$value                         ;;
                 dpi=*)      CMD_DPI=$value                         ;;
                 kbd=*)      CMD_KBD=$value ;          DO_XKBD=true ;;
               kbopt=*)   XKBOPTIONS=$value ;          DO_XKBD=true ;;
               kbvar=*)   XKBVARIANT=$value ;          DO_XKBD=true ;;
                lang=*)     CMD_LANG=$value ;          DO_XKBD=true ;;
              mirror=*)   CMD_MIRROR=$value                         ;;
         hwclock=local)   CMD_CLOCK=$value                          ;;
           hwclock=utc)   CMD_CLOCK=$value                          ;;

              failsafe)   XORG_ARGS=$XORG_ARGS${XORG_ARGS:+,}safe   ;;
                xorg=*)   XORG_ARGS=$XORG_ARGS${XORG_ARGS:+,}$value ;;
                noxorg)   NO_XORG=true                              ;;

automount=off|amnt=off)                          AUTOMOUNT_OFF=true ;;
        automount|amnt)                              AUTOMOUNT=true ;;
    automount=*|amnt=*)    CMD_MOUNT=$value ;        AUTOMOUNT=true ;;
               mount=*)    CMD_MOUNT=$value ;        AUTOMOUNT=true ;;
               fstab=*)    CMD_FSTAB=$value                         ;;
                splash) SPLASH_PARAM=v                              ;;
              splash=*) SPLASH_PARAM=$value                         ;;

    esac
done

PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/live/bin"; export PATH

umask 022

# . /usr/share/antiX/lib/live-init-utils.sh
. /live/lib/live-init-utils.sh

start_init_logging
load_translation

main() {
    case "$1" in
        start)
            do_start
            ;;
        stop)
            exit 0
            ;;
        *)
            echo "Usage: $0 {start|stop}"
            exit 1
            ;;
    esac
}

#----- Main code starts here --------------------------------------------------

do_start() {
    echo_script "Localizing/configuring X-Windows" $0

    local DISTRO="unknown"
    get_init_param DISTRO

    case $DISTRO in
        antiX) automount_and_fstab;;
      MX|MX-*) add_fstab_swap     ;;
            *) error 'Unknown_distro %s' "$(pquote $DISTRO)"
    esac

    #-jbb: for debugging
    unset COUNTRY WM_LANG KEYBOARDS KEYTABLE LANG MIRROR TZ XKBLAYOUT CONSOLE_FONT
    [ "$CMD_LANG" ] && get_init_lang $CMD_LANG error

    MIRROR=${CMD_MIRROR:-$MIRROR}
    [ "$MIRROR" ] && set_mirror $MIRROR

    [ "$WM_LANG" ] && localize_skel $WM_LANG

    # Always create keyboard file in non-perisistent system even with no X
    kb_file=/etc/default/keyboard
    default_xkb_opts="grp:alt_shift_toggle,terminate:ctrl_alt_bksp,grp_led:scroll"

    if first_write $kb_file || [ "$DO_XKBD" ]; then
        XKBLAYOUT=${CMD_KBD:-$XKBLAYOUT}
        [ "$XKBLAYOUT"  ] && echo_live "Setting %s to %s" $(pquote xkb-layout)  $(pquote $XKBLAYOUT)
        [ "$XKBMODEL"   ] && echo_live "Setting %s to %s" $(pquote xkb-model)   $(pquote $XKBMODEL)
        [ "$XKBVARIANT" ] && echo_live "Setting %s to %s" $(pquote xkb-variant) $(pquote $XKBVARIANT)
        [ "$XKBOPTIONS" ] && echo_live "Setting %s to %s" $(pquote xkb-options) $(pquote $XKBOPTIONS)

        cat > $kb_file <<Keyboard_Out
XKBMODEL="${XKBMODEL:=pc105}"
XKBLAYOUT="${XKBLAYOUT:=us}"
XKBVARIANT="${XKBVARIANT}"
XKBOPTIONS="${XKBOPTIONS:=$default_xkb_opts}"
Keyboard_Out
    fi

    [ "$CMD_CLOCK"   ] && set_utc_local $CMD_CLOCK

    # Don't bother with X stuff on systems without X
    #--------------------------------------------------------------------------
    if [ ! -d "$XSESSION_DIR" ]; then
        create_home
        exit 0
    fi
    #--------------------------------------------------------------------------

    [ "$CMD_DPI" ] && set_dpi $CMD_DPI

    [ "$NO_XORG" ] || make_xorg_conf

    create_home

    [ "$CMD_DESKTOP" ] && set_default_desktop $CMD_DESKTOP

    #localize_firefox $LANG

    enable_xkb="s/^#\?setxkbmap.*/setxkbmap -layout \"$XKBLAYOUT\" -option \"$XKBOPTIONS\" -variant \"$XKBVARIANT\"/"

    for wm in $MENU_WMs;  do
        f1=/home/demo/.$wm/startup
        f2=/etc/skel/.$wm/menu
        f3=/etc/skel/.config/rox.sourceforge.net/ROX-Filer/pb_antiX-$wm
        f4=/etc/skel/.$wm/startup
        [ -e $f1 ] && sed -i -e "$enable_xkb"             $f1
        [ -e $f2 ] && sed -i -e "/gksu antixsources.sh/d" $f2
        [ -e $f3 ] && sed -i -e "/antixsources.desktop/d" $f3
        [ -e $f4 ] && sed -i -e "/toram-eject/d"          $f4
        [ -e $f4 ] && sed -i -e "/persist-config/d"       $f4
        rm -f /etc/skel/Desktop/Install.desktop
    done
}

create_home() {
    local user=demo
    local home=/home/$user

    # Find $user user with home at $home
    if ! grep -q "^$user:[^:]*:[^:]*:[^:]*:[^:]*:$home:" /etc/passwd; then
        echo_live "No %s user found.  Not populating %s." $(pquote $user) $(pquote $home)
        return
    fi

    rmdir $demo 2>/dev/null
    if test -d $home; then
        echo_live "Files already exist under %s" $(pquote $home)
        echo_live "Not creating or populating %s" $(pquote $home)
        return
    fi

    echo_live "Populating %s directory" $(pquote $home)

    mkdir -p $home
    cp -r -P -p mode /etc/skel/* /etc/skel/.[a-zA-Z]* $home 2>/dev/null
    chown -R $user:users $home 2>/dev/null
}

localize_skel() {
    local l10n_dir=/usr/share/antiX/localisation
    local from=$l10n_dir/$1
    local dest=/etc/skel

    # Silently skip systems which have no localisation directory
    [ -d "$l10n_dir" ] || return

    if ! [ -d $from ]; then
        error "Unknown menu localization language %s" $(pquote $1)
        error "Directory not found %s" $from
        return
    fi

    echo_live "Localizing menus to %s in %s" $(pquote $0) $(pquote $dest)

    # Basically a cp -a but make all top level files and directories hidden
    for file in $(ls $from); do
       if [ -d $from/$file ]; then
           mkdir -p /$dest/.$file
           cp -a $from/$file/* $dest/.$file
       else
           rm -rf $dest/.$file
           cp -a $from/$file $dest/.$file
       fi
    done
}

#FIXME:
localize_firefox() {
    local pref_files file lang=$1
    local string="user_pref(\"spellchecker.dictionary\","

    pref_files=$(ls $FF_PREFS 2>/dev/null)
    [ "$pref_files" ] || return
    sed -i  "/$string/d" $pref_files
    for file in $pref_files; do
        echo "$string \"$lang\");" >> $file
    done
}

set_dpi() {
    local dpi=$1

    if ! echo $dpi | grep -q "^[[:digit:]]\+$"; then
        error "Invalid %s boot parameter %s" $(pquote dpi) $(pquote $dpi)
        return
    fi

    echo_live "Setting %s to %s" $(pquote dpi) $(pquote $dpi)

    local file
    for file in /etc/slim.conf /usr/share/slim/themes/antiX/slim-install.conf; do
        [ -e $file ] || continue
        sed -i -e "s/^xserver_arguments.*/xserver_arguments -dpi $dpi -nolisten tcp/" $file
    done

    for file in /etc/lightdm/lightdm.conf; do
        [ -e $file ] || continue
        sed -i -r "s/^#?\s*(xserver-command=X).*/\1 -dpi $dpi/" $file
    done
}

set_mirror() {
    local mirror=$1

    if [ -z "$mirror" -o -n "${mirror##[a-zA-Z][a-zA-Z]}" ]; then
        error "Bad mirror code %s (expected two letters)" $(pquote $mirror)
        return
    fi

    source_list=/etc/apt/sources.list.d/debian.list

    first_write $source_list || [ "$CMD_MIRROR" ] || return

    echo_live "Localizing %s to %s mirror" $(pquote $source_list) $(pquote $mirror)
    sed -i "s=/ftp\.\(..\.\)\\?debian\.org/=/ftp.$mirror.debian.org/=" $source_list
}

set_utc_local() {
    local new=$1 file=/etc/adjtime
    #grep -i -q $new $file && return

    echo_live "Assuming %s is set to %s time" hwclock $(pquote $new)

    case $new in
        local) sed -i 's/^UTC\s*$/LOCAL/' $file
               hwclock --hctosys --localtime      ;;
          utc) sed -i 's/^LOCAL\s*$/UTC/' $file
               hwclock --hctosys --utc            ;;
    esac
}

set_default_desktop() {
    local desktop=$1 desktop_file=/home/demo/.desktop-session/default-desktop
    echo_live "Setting %s to %s" desktop $(pquote $desktop)
    echo $desktop > $desktop_file
}

add_fstab_swap() {
    echo_live 'Possibly adding swap partitions to fstab'
    make-fstab --quiet --swap-only
}

automount_and_fstab() {

   local        am_file=/etc/fstab.automount
   local     mount_file=/etc/fstab.mount
   local        hp_file=/etc/fstab.hotplug
   local  hp_state_file=$hp_file.state

    # "off" means "off"
    if [ "$CMD_MOUNT" = 'off' -o -n "$AUTOMOUNT_OFF" ]; then
        echo_live "Turning all boot mount options off"
        rm -f $mount_file
        CMD_MOUNT=

        if [ -n "$AUTOMOUNT_OFF" ]; then
            echo_live "Turning automount off"
            AUTOMOUNT=
            rm -f $am_file
        fi
    fi

    # Read in previous value (persistent systems only)
    if [ -z "$CMD_MOUNT" -a -e $mount_file ]; then
        CMD_MOUNT=$(cat $mount_file)
    else
        [ "$CMD_MOUNT" ] && echo $CMD_MOUNT > $mount_file
    fi

    # Mount partitions while building fstab file
    local fstab_opt=
    case ",$CMD_MOUNT" in
        ,all|,usb)
            fstab_opt="$fstab_opt --mount=$CMD_MOUNT" ;;
        ,)
            ;;
        *)
            error "Invalid %s option %s" 'mount/automount' $(pquote $CMD_MOUNT)
    esac

    if [ -e /etc/fstab  ]; then
        grep -q -e ^/dev -e ^UUID= -e ^LABEL=  /etc/fstab || rm /etc/fstab
    fi

    make-fstab --quiet $fstab_opt

    [ "$AUTOMOUNT" ] && touch $am_file

    if [ -e $am_file ]; then
        echo_live "Automount enabled"
    else
        echo_live "Automount disabled"
    fi

    # The hp_file is removed by /init
    # The hp_state_file carries over "off" setting on persistent systems
    [ -z "$CMD_FSTAB" -a -e $hp_state_file ] && CMD_FSTAB=$(cat $hp_state_file)

    case ",$CMD_FSTAB" in
        ,off)
            echo_live "Disabling fstab hotplugging (this will also disable automount)"
            echo $CMD_FSTAB > $hp_state_file
            rm -f $hp_file  ;;

        ,on|,)
            echo_live "Enabling fstab hotplugging"
            rm -f $hp_state_file
            touch $hp_file;;

        *)
            error "Bad fstab option %s" $(pquote $CMD_FSTAB)
            echo_live "Enabling fstab hotplugging"
            touch $hp_file;;
    esac
}

make_xorg_conf() {
    local xorg_conf=/etc/X11/xorg.conf
    local orig_fb_name fb_name=none
    read orig_fb_name 2</dev/null < /sys/class/graphics/fb0/name
    echo_live "Scanning for hardware specific video modules ..."
    local video_modules="$(find_video_modules)"
    local kms_modules="$(echo "$video_modules" | egrep "^($KMS_VIDEO_MODULES)$")"

    if [ "$kms_modules" ]; then
        echo_live "Found %s video module(s) %s" KMS "$(pquote $(echo $kms_modules))"
        echo_live "Load module(s) %s" "$(pquote $(echo $kms_modules))"
        modprobe -a -q "$kms_modules"
        set_fbcondecor "$SPLASH_PARAM" "$orig_fb_name"
    elif [ "$video_modules" ]; then
        echo_live "Found video module(s) %s" "$(pquote $(echo $video_modules))"
    fi

    # Always erase generated xorg.conf files
    test -f $xorg_conf && grep -q "*#\s*Generated by\s*make-xorg-conf" $xorg_conf \
        && rm -f $xorg_conf

    # Check who is creating the framebuffer (in any)
    local vga_fb fb_name=none
    read fb_name 2>/dev/null < /sys/class/graphics/fb0/name

    case $fb_name in
      "VESA VGA") vga_fb=true ;;
    esac

    # Force X video driver to be vesa if the vga framebuffer is enabled.
    # Only force creation of safe xorg.conf if a custom xorg.conf does not
    # already exists
    if  [ "$vga_fb" -a ! -e $xorg_conf ]; then
        echo_live "Forcing X-windows to use safe mode"
        XORG_ARGS=safe${XORG_ARGS:+,}$XORG_ARGS
    fi

    [ "$XORG_ARGS" ] || return

    echo_live "Configuring %s file with %s" $(pquote $xorg_conf) $(pquote $XORG_ARGS)
    backup_file $xorg_conf
    /sbin/make-xorg-conf --file=$xorg_conf $XORG_ARGS
}

find_video_modules() {
    find /sys/devices -name modalias -print0 | xargs -0 sort -u \
        | xargs modprobe -a -D -q 2>/dev/null | sort -u \
        | sed -n -r "s/^insmod [^ ]*($ALL_VIDEO_MODULES)\.ko.*/\1/p"
}

set_fbcondecor() {
    local boot_param=$1 orig_name=$2 param verbose theme=default
    [ "$orig_name"  ] || return
    [ "$boot_param" ] || return

    local new_name=$(cat /sys/class/graphics/fb0/name 2>/dev/null)
    [ "$orig_name" = "$new_name" ] && return

    for param in $(echo $boot_param | sed "s/,/ /g"); do
        case $param in
            v|verbose) verbose=true ;;
          t=*|theme=*) theme=${param#*=} ;;
        esac
    done

    # Only set bg if we are in verbose mode
    [ "$verbose" ] || return
    /sbin/splash-term $theme
}
# Always copy to $file$ext2 so this has the most recent backup.
# Only move to $file$ext1 if it does not already exist so this will
# contain the earliest (oldest) backup.

backup_file() {
    local file=$1 ext1=${2:-.old} ext2=${3:-save}

    test -e $file || return
    cp -f $file $file$ext2
    test -e $file$ext1 && return
    mv -f $file $file$ext1
}

main "$@" 2>&1 | tee -a $INIT_LOG_FILE

exit 0
