#!/bin/sh

### BEGIN INIT INFO
# Provides:          persist-autosave
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:       Run persist-config on startup if needed.  Run persist-save if needed
### END INIT INFO

[ -e /live/config/save-persist ] || return 0
PATH=$PATH:/usr/local/bin

persist_conf=/etc/live/config/persist-config.conf
new_passwd=/live/config/new-passwords

start() {
    # Bail early if no persist-config is needed
    if [ -e $persist_conf ]; then
        # But still do a persist-save if there are new passwords
        [ -e $new_passwd ] || exit 0
        echo_live "Saving new passwords in persistence file"
        persist-save --quiet -cli --nolog
        exit 0
    fi

    persist-config --cli --startup --nolog
    [ -e $persist_conf -o -e $new_passwd ] || exit 0
    [ -e $new_passwd ]   && echo_live "Save new passwords"
    [ -e $persist_conf ] && echo_live "Save new autosave selection"

    persist-save --quiet -cli --nolog
}

case $1 in
    start) start                   ;;
        *)echo "Usage: $0 {start}" ;;
esac

exit 0
