#!/bin/sh

### BEGIN INIT INFO
# Provides:          persist-autosave
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:       Run persist-config on startup if needed.  Run persist-save if needed
### END INIT INFO

[ -e /live/config/persist-save ] || return 0
PATH=$PATH:/usr/local/bin

start() {
    # Bail early if no persist-config is needed
    if [ ! -e /etc/live/config/persist-config.conf ]; then
        # But still do a persist-save if there are new passwords
        [ -e /live/config/new-passwords ] || return 0
        echo_live "Saving new passwords in persistence file"
        persist-save --quiet -cli --nolog
        return 0
    fi
    /usr/local/bin/persist-config --cli --startup --nolog

}

case $1 in
    start) start                   ;;
        *)echo "Usage: $0 {start}" ;;
esac

exit 0

